-- =====================================================================
-- SAP Enterprise Ontology — 04: knowledge graph instances and edges
--
-- The graph holds identities and relationships; transactions stay in the
-- source databases and are reached through the ANALYTICS facts and views.
-- Edge WEIGHT carries the money or volume that makes the link matter.
-- Rebuilt in full each run (idempotent).
-- =====================================================================
USE DATABASE SAP_ENTERPRISE_ONTOLOGY;
TRUNCATE TABLE CORE.KG_NODE;
TRUNCATE TABLE CORE.KG_EDGE;

-- ---------------------------------------------------------------- schema nodes
INSERT INTO CORE.KG_NODE (NODE_ID, NODE_TYPE, NAME, PROPS, TS_INGESTED, MODULE)
SELECT 'class:' || CLASS_NAME, 'OntologyClass', CLASS_NAME,
       OBJECT_CONSTRUCT('description', DESCRIPTION, 'is_abstract', IS_ABSTRACT, 'parent', PARENT_CLASS_NAME, 'module', MODULE),
       CURRENT_TIMESTAMP(), MODULE
FROM CORE.ONT_CLASS;
INSERT INTO CORE.KG_EDGE (EDGE_ID, SRC_ID, DST_ID, EDGE_TYPE, WEIGHT, PROPS, TS_INGESTED, MODULE)
SELECT 'sub:' || CLASS_NAME, 'class:' || CLASS_NAME, 'class:' || PARENT_CLASS_NAME, 'subClassOf', 1, NULL, CURRENT_TIMESTAMP(), MODULE
FROM CORE.ONT_CLASS WHERE PARENT_CLASS_NAME IS NOT NULL;

-- ---------------------------------------------------------------- golden nodes (CORE), props = their 360 facts
INSERT INTO CORE.KG_NODE (NODE_ID, NODE_TYPE, NAME, PROPS, TS_INGESTED, MODULE)
SELECT 'CO:' || COMPANY_CODE, 'LegalEntity', COMPANY, OBJECT_CONSTRUCT(*), CURRENT_TIMESTAMP(), 'CORE' FROM ANALYTICS.DT_COMPANY_360
UNION ALL SELECT 'GC:' || CUSTOMER_ID, 'Customer', CUSTOMER, OBJECT_CONSTRUCT(*), CURRENT_TIMESTAMP(), 'CORE' FROM ANALYTICS.DT_CUSTOMER_360
UNION ALL SELECT 'GS:' || SUPPLIER_ID, 'Supplier', SUPPLIER, OBJECT_CONSTRUCT(*), CURRENT_TIMESTAMP(), 'CORE' FROM ANALYTICS.DT_SUPPLIER_360
UNION ALL SELECT 'DEP:' || GOLDEN_ID, 'Department', NAME, OBJECT_CONSTRUCT('fin_code', FIN_CODE, 'match_method', MATCH_METHOD), CURRENT_TIMESTAMP(), 'CORE'
            FROM XWALK.GOLDEN_DEPARTMENT;

-- ---------------------------------------------------------------- local members + sameAs
INSERT INTO CORE.KG_NODE (NODE_ID, NODE_TYPE, NAME, PROPS, TS_INGESTED, MODULE)
SELECT 'LC:' || MODULE || ':' || LOCAL_ID, 'LocalCustomer', COALESCE(LOCAL_NAME, LOCAL_ID),
       OBJECT_CONSTRUCT('local_id', LOCAL_ID, 'match_method', MATCH_METHOD), CURRENT_TIMESTAMP(), MODULE FROM XWALK.CUSTOMER_MEMBER
UNION ALL
SELECT 'LS:' || MODULE || ':' || LOCAL_ID, 'LocalSupplier', COALESCE(LOCAL_NAME, LOCAL_ID),
       OBJECT_CONSTRUCT('local_id', LOCAL_ID, 'match_method', MATCH_METHOD), CURRENT_TIMESTAMP(), MODULE FROM XWALK.SUPPLIER_MEMBER;
INSERT INTO CORE.KG_EDGE (EDGE_ID, SRC_ID, DST_ID, EDGE_TYPE, WEIGHT, PROPS, TS_INGESTED, MODULE)
SELECT 'sa:' || MODULE || ':' || LOCAL_ID, 'LC:' || MODULE || ':' || LOCAL_ID, 'GC:' || GOLDEN_ID, 'sameAs', 1,
       OBJECT_CONSTRUCT('match_method', MATCH_METHOD), CURRENT_TIMESTAMP(), 'CORE' FROM XWALK.CUSTOMER_MEMBER
UNION ALL
SELECT 'ss:' || MODULE || ':' || LOCAL_ID, 'LS:' || MODULE || ':' || LOCAL_ID, 'GS:' || GOLDEN_ID, 'sameAsSupplier', 1,
       OBJECT_CONSTRUCT('match_method', MATCH_METHOD), CURRENT_TIMESTAMP(), 'CORE' FROM XWALK.SUPPLIER_MEMBER;

-- ---------------------------------------------------------------- module nodes
INSERT INTO CORE.KG_NODE (NODE_ID, NODE_TYPE, NAME, PROPS, TS_INGESTED, MODULE)
SELECT 'PLT:' || p.PLANT, 'Plant', p.PLANT_NAME, OBJECT_CONSTRUCT('plant', p.PLANT, 'city', p.CITY, 'company_code_local', p.COMPANY_CODE),
       CURRENT_TIMESTAMP(), 'SCM' FROM SAP_SUPPLY_CHAIN.PLANT.A_PLANT p
UNION ALL
SELECT 'EQ:' || EQUIPMENT_ID, 'Equipment', EQUIPMENT_NAME,
       OBJECT_CONSTRUCT('plant', PLANT, 'failure_prob_48h', FAILURE_PROB_48H, 'anomaly', ANOMALY_FLAG, 'work_center', WORK_CENTER_DESC),
       CURRENT_TIMESTAMP(), 'SCM'
FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_EQUIPMENT_HEALTH QUALIFY ROW_NUMBER() OVER (PARTITION BY EQUIPMENT_ID ORDER BY READING_DATE DESC) = 1
UNION ALL
SELECT DISTINCT 'CC:' || COMPANYCODE || ':' || COSTCENTER, 'CostCenter', COSTCENTER || ' (' || DEPARTMENT || ')',
       OBJECT_CONSTRUCT('company_code', COMPANYCODE, 'department_code', DEPARTMENT), CURRENT_TIMESTAMP(), 'FIN'
FROM SAP_FINANCE_360.ANALYTICS.DT_EXPENSE_BY_COSTCENTER
UNION ALL
SELECT 'CAT:' || CATEGORY, 'SpendCategory', CATEGORY, OBJECT_CONSTRUCT('suppliers', COUNT(DISTINCT SUPPLIER)), CURRENT_TIMESTAMP(), 'SPD'
FROM SAP_SPEND_360.ANALYTICS.DT_SPEND_360 GROUP BY CATEGORY
UNION ALL
SELECT 'EMP:' || EMPLOYEE_ID, 'Employee', JOB_TITLE || ' · ' || EMPLOYEE_ID,
       OBJECT_CONSTRUCT('department', DEPARTMENT, 'company', COMPANY, 'status', EMPLOYMENT_STATUS, 'critical', IS_CRITICAL_POSITION),
       CURRENT_TIMESTAMP(), 'PPL'
FROM SAP_PEOPLE_360.ANALYTICS.DT_WORKFORCE_360 WHERE EMPLOYMENT_STATUS = 'Active';

-- ---------------------------------------------------------------- cross-domain edges
INSERT INTO CORE.KG_EDGE (EDGE_ID, SRC_ID, DST_ID, EDGE_TYPE, WEIGHT, PROPS, TS_INGESTED, MODULE)
-- Plant ownedBy LegalEntity (SCM -> CORE)
SELECT 'own:' || p.PLANT, 'PLT:' || p.PLANT, 'CO:' || m.GOLDEN_ID, 'ownedBy', 1, NULL, CURRENT_TIMESTAMP(), 'SCM'
FROM SAP_SUPPLY_CHAIN.PLANT.A_PLANT p JOIN XWALK.COMPANY_MEMBER m ON m.MODULE = 'SCM' AND m.LOCAL_ID = p.COMPANY_CODE
UNION ALL
-- LegalEntity employs Employee, Employee inDepartment Department (PPL)
SELECT 'emp:' || w.EMPLOYEE_ID, 'CO:' || m.GOLDEN_ID, 'EMP:' || w.EMPLOYEE_ID, 'employs', 1, NULL, CURRENT_TIMESTAMP(), 'PPL'
FROM SAP_PEOPLE_360.ANALYTICS.DT_WORKFORCE_360 w JOIN XWALK.COMPANY_MEMBER m ON m.MODULE = 'PPL' AND m.LOCAL_ID = w.COMPANY
WHERE w.EMPLOYMENT_STATUS = 'Active'
UNION ALL
SELECT 'dep:' || w.EMPLOYEE_ID, 'EMP:' || w.EMPLOYEE_ID, 'DEP:' || d.GOLDEN_ID, 'inDepartment', 1, NULL, CURRENT_TIMESTAMP(), 'PPL'
FROM SAP_PEOPLE_360.ANALYTICS.DT_WORKFORCE_360 w JOIN XWALK.GOLDEN_DEPARTMENT d ON d.NAME = w.DEPARTMENT
WHERE w.EMPLOYMENT_STATUS = 'Active'
UNION ALL
-- Department fundedBy CostCenter (FIN), weight = expense USD
SELECT 'fund:' || e.COMPANYCODE || ':' || e.COSTCENTER, 'DEP:' || d.GOLDEN_ID, 'CC:' || e.COMPANYCODE || ':' || e.COSTCENTER, 'fundedBy',
       SUM(e.EXPENSE_AMOUNT * fx.RATE_TO_USD), NULL, CURRENT_TIMESTAMP(), 'FIN'
FROM SAP_FINANCE_360.ANALYTICS.DT_EXPENSE_BY_COSTCENTER e
JOIN XWALK.GOLDEN_DEPARTMENT d ON d.FIN_CODE = e.DEPARTMENT
JOIN XWALK.GOLDEN_COMPANY c ON c.GOLDEN_ID = e.COMPANYCODE JOIN ANALYTICS.FX fx ON fx.CURRENCY = c.CURRENCY
GROUP BY e.COMPANYCODE, e.COSTCENTER, d.GOLDEN_ID
UNION ALL
-- LegalEntity buysFrom Supplier (SPD), weight = spend USD
SELECT 'buy:' || mc.GOLDEN_ID || ':' || ms.GOLDEN_ID, 'CO:' || mc.GOLDEN_ID, 'GS:' || ms.GOLDEN_ID, 'buysFrom',
       SUM(s.SPEND * fx.RATE_TO_USD), NULL, CURRENT_TIMESTAMP(), 'SPD'
FROM SAP_SPEND_360.ANALYTICS.DT_SPEND_360 s
JOIN XWALK.COMPANY_MEMBER mc ON mc.MODULE = 'SPD' AND mc.LOCAL_ID = s.COMPANY
JOIN XWALK.SUPPLIER_MEMBER ms ON ms.MODULE = 'SPD' AND ms.LOCAL_ID = s.SUPPLIER
JOIN ANALYTICS.FX fx ON fx.CURRENCY = s.CURRENCY GROUP BY mc.GOLDEN_ID, ms.GOLDEN_ID
UNION ALL
-- LegalEntity owesTo Supplier (WCP), weight = open AP USD
SELECT 'owe:' || a.COMPANY_CODE || ':' || ms.GOLDEN_ID, 'CO:' || a.COMPANY_CODE, 'GS:' || ms.GOLDEN_ID, 'owesTo',
       SUM(IFF(a.IS_OPEN, a.AMOUNT_USD, 0)), NULL, CURRENT_TIMESTAMP(), 'WCP'
FROM SAP_WORKING_CAPITAL_360.ANALYTICS.DT_AP_ITEMS a
JOIN XWALK.SUPPLIER_MEMBER ms ON ms.MODULE = 'WCP' AND ms.LOCAL_ID = a.SUPPLIER_ID GROUP BY a.COMPANY_CODE, ms.GOLDEN_ID
UNION ALL
-- LegalEntity sellsToCustomer Customer (WCP), weight = AR USD
SELECT 'sell:' || a.COMPANY_CODE || ':' || mc.GOLDEN_ID, 'CO:' || a.COMPANY_CODE, 'GC:' || mc.GOLDEN_ID, 'sellsToCustomer',
       SUM(a.AMOUNT_USD), NULL, CURRENT_TIMESTAMP(), 'WCP'
FROM SAP_WORKING_CAPITAL_360.ANALYTICS.DT_AR_ITEMS a
JOIN XWALK.CUSTOMER_MEMBER mc ON mc.MODULE = 'WCP' AND mc.LOCAL_ID = a.CUSTOMER_ID GROUP BY a.COMPANY_CODE, mc.GOLDEN_ID
UNION ALL
-- Plant shipsTo Customer (SCM), weight = order value USD
SELECT 'ship:' || o.PLANT || ':' || mc.GOLDEN_ID, 'PLT:' || o.PLANT, 'GC:' || mc.GOLDEN_ID, 'shipsTo',
       SUM(o.NET_VALUE_USD), OBJECT_CONSTRUCT('late_cost_usd', SUM(o.LATE_COST_USD), 'otif_pct', ROUND(100 * COUNT_IF(o.OTIF) / COUNT(*), 1)),
       CURRENT_TIMESTAMP(), 'SCM'
FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_ORDER_FULFILLMENT o
JOIN SAP_SUPPLY_CHAIN.ONTOLOGY.KG_NODE n ON n.NODE_TYPE = 'Customer' AND n.NAME = o.SOLD_TO
JOIN XWALK.CUSTOMER_MEMBER mc ON mc.MODULE = 'SCM' AND mc.LOCAL_ID = n.NODE_ID GROUP BY o.PLANT, mc.GOLDEN_ID
UNION ALL
-- Supplier supplies Plant (SCM), weight = component lots consumed
SELECT 'sup:' || ms.GOLDEN_ID || ':' || g.PLANT, 'GS:' || ms.GOLDEN_ID, 'PLT:' || g.PLANT, 'supplies',
       COUNT(DISTINCT g.LOT_ID), OBJECT_CONSTRUCT('deviating_lots', COUNT(DISTINCT IFF(g.INSPECTION_RESULT <> 'Accepted', g.LOT_ID, NULL))),
       CURRENT_TIMESTAMP(), 'SCM'
FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_SERIAL_GENEALOGY g
JOIN XWALK.SUPPLIER_MEMBER ms ON ms.MODULE = 'SCM' AND ms.LOCAL_ID = g.SUPPLIER GROUP BY ms.GOLDEN_ID, g.PLANT
UNION ALL
-- Equipment installedAt Plant (SCM)
SELECT 'inst:' || EQUIPMENT_ID, 'EQ:' || EQUIPMENT_ID, 'PLT:' || ANY_VALUE(PLANT), 'installedAt', 1, NULL, CURRENT_TIMESTAMP(), 'SCM'
FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_EQUIPMENT_HEALTH GROUP BY EQUIPMENT_ID
UNION ALL
-- Supplier inCategory SpendCategory (SPD), weight = spend USD
SELECT 'cat:' || ms.GOLDEN_ID || ':' || s.CATEGORY, 'GS:' || ms.GOLDEN_ID, 'CAT:' || s.CATEGORY, 'inCategory',
       SUM(s.SPEND * fx.RATE_TO_USD), NULL, CURRENT_TIMESTAMP(), 'SPD'
FROM SAP_SPEND_360.ANALYTICS.DT_SPEND_360 s
JOIN XWALK.SUPPLIER_MEMBER ms ON ms.MODULE = 'SPD' AND ms.LOCAL_ID = s.SUPPLIER
JOIN ANALYTICS.FX fx ON fx.CURRENCY = s.CURRENCY GROUP BY ms.GOLDEN_ID, s.CATEGORY;

-- ---------------------------------------------------------------- abstract views (Supply Chain pattern)
CREATE OR REPLACE VIEW CORE.VW_ONT_PARTY AS
  SELECT NODE_ID, NODE_TYPE, NAME, MODULE, PROPS FROM CORE.KG_NODE
  WHERE NODE_TYPE IN ('Customer', 'Supplier', 'Employee', 'LocalCustomer', 'LocalSupplier');
CREATE OR REPLACE VIEW CORE.VW_ONT_ORGUNIT AS
  SELECT NODE_ID, NODE_TYPE, NAME, MODULE, PROPS FROM CORE.KG_NODE
  WHERE NODE_TYPE IN ('LegalEntity', 'Department', 'CostCenter');
CREATE OR REPLACE VIEW CORE.VW_ONT_FACILITY AS
  SELECT NODE_ID, NODE_TYPE, NAME, MODULE, PROPS FROM CORE.KG_NODE WHERE NODE_TYPE = 'Plant';

-- Cross-module paths that only the master ontology can answer.
-- Supplier -> plants it feeds -> customers those plants ship to: who is exposed to a supplier.
CREATE OR REPLACE VIEW CORE.VW_SUPPLIER_TO_CUSTOMER_EXPOSURE AS
SELECT s.NAME AS SUPPLIER, s.NODE_ID AS SUPPLIER_ID, p.NAME AS PLANT, c.NAME AS CUSTOMER, c.NODE_ID AS CUSTOMER_ID,
       e2.WEIGHT AS ORDER_VALUE_USD, e2.PROPS:late_cost_usd::NUMBER AS LATE_COST_USD,
       e1.PROPS:deviating_lots::NUMBER AS DEVIATING_LOTS_INTO_PLANT
FROM CORE.KG_EDGE e1
JOIN CORE.KG_NODE s ON s.NODE_ID = e1.SRC_ID
JOIN CORE.KG_NODE p ON p.NODE_ID = e1.DST_ID
JOIN CORE.KG_EDGE e2 ON e2.SRC_ID = p.NODE_ID AND e2.EDGE_TYPE = 'shipsTo'
JOIN CORE.KG_NODE c ON c.NODE_ID = e2.DST_ID
WHERE e1.EDGE_TYPE = 'supplies';

-- Supplier quality exposure: customer order value that actually contains a deviating
-- lot from the supplier (golden supplier -> SCM lots -> serials -> orders -> golden customer).
-- Reduced to one row per (supplier, order) before summing, so an order with several
-- deviating lots is counted once.
CREATE OR REPLACE VIEW CORE.VW_SUPPLIER_QUALITY_EXPOSURE AS
WITH hits AS (
  SELECT ms.GOLDEN_ID AS SUPPLIER_ID, g.SALES_ORDER,
         COUNT(DISTINCT g.LOT_ID) AS DEVIATING_LOTS, COUNT(DISTINCT g.SERIAL_NO) AS SYSTEMS
  FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_SERIAL_GENEALOGY g
  JOIN XWALK.SUPPLIER_MEMBER ms ON ms.MODULE = 'SCM' AND ms.LOCAL_ID = g.SUPPLIER
  WHERE g.INSPECTION_RESULT <> 'Accepted'
  GROUP BY 1, 2)
SELECT h.SUPPLIER_ID, gs.SUPPLIER, mc.GOLDEN_ID AS CUSTOMER_ID, gc.CUSTOMER,
       SUM(h.DEVIATING_LOTS) AS DEVIATING_LOT_HITS, SUM(h.SYSTEMS) AS SYSTEMS, COUNT(*) AS ORDERS,
       SUM(o.NET_VALUE_USD) AS ORDER_VALUE_USD, SUM(o.LATE_COST_USD) AS LATE_COST_USD
FROM hits h
JOIN SAP_SUPPLY_CHAIN.ANALYTICS.DT_ORDER_FULFILLMENT o ON o.SALES_ORDER = h.SALES_ORDER
JOIN SAP_SUPPLY_CHAIN.ONTOLOGY.KG_NODE n ON n.NODE_TYPE = 'Customer' AND n.NAME = o.SOLD_TO
JOIN XWALK.CUSTOMER_MEMBER mc ON mc.MODULE = 'SCM' AND mc.LOCAL_ID = n.NODE_ID
JOIN ANALYTICS.DT_SUPPLIER_360 gs ON gs.SUPPLIER_ID = h.SUPPLIER_ID
JOIN ANALYTICS.DT_CUSTOMER_360 gc ON gc.CUSTOMER_ID = mc.GOLDEN_ID
GROUP BY 1, 2, 3, 4;
