-- Fix: the generated graph traversal UDFs resolve a concept with
--   WHERE LOWER(NAME) = LOWER(<arg>) LIMIT 1
-- with no ORDER BY and no NODE_TYPE filter. KG_NODE holds BOTH ontology schema
-- nodes (NODE_TYPE='OntologyClass') and instance nodes, and names collide:
-- 'Supplier' matches a CDSEntity, a DataProduct and the OntologyClass. The UDF
-- picked an arbitrary one, so traversal silently returned zero rows.
-- Every concept lookup below is pinned to NODE_TYPE = 'OntologyClass'.

CREATE OR REPLACE FUNCTION SAP_SUPPLY_CHAIN.ONTOLOGY.GET_ANCESTORS_TOOL(CONCEPT VARCHAR)
RETURNS TABLE (ANCESTOR_ID VARCHAR, ANCESTOR_NAME VARCHAR, DEPTH NUMBER)
LANGUAGE SQL
COMMENT='Returns all ancestors of a concept. Use for understanding where a concept sits in the hierarchy.'
AS
$$
WITH RECURSIVE
start_node AS (
    SELECT NODE_ID, NAME FROM SAP_SUPPLY_CHAIN.ONTOLOGY.KG_NODE
    WHERE LOWER(NAME) = LOWER(CONCEPT) AND NODE_TYPE = 'OntologyClass'
    ORDER BY NODE_ID LIMIT 1
),
ancestors AS (
    SELECT e.DST_ID AS ANCESTOR_ID, n.NAME AS ANCESTOR_NAME, 1 AS DEPTH
    FROM start_node s
    JOIN SAP_SUPPLY_CHAIN.ONTOLOGY.KG_EDGE e ON s.NODE_ID = e.SRC_ID
    JOIN SAP_SUPPLY_CHAIN.ONTOLOGY.KG_NODE n ON e.DST_ID = n.NODE_ID
    WHERE e.EDGE_TYPE = 'subClassOf'
    UNION ALL
    SELECT e.DST_ID, n.NAME, a.DEPTH + 1
    FROM ancestors a
    JOIN SAP_SUPPLY_CHAIN.ONTOLOGY.KG_EDGE e ON a.ANCESTOR_ID = e.SRC_ID
    JOIN SAP_SUPPLY_CHAIN.ONTOLOGY.KG_NODE n ON e.DST_ID = n.NODE_ID
    WHERE e.EDGE_TYPE = 'subClassOf' AND a.DEPTH < 20
)
SELECT ANCESTOR_ID, ANCESTOR_NAME, MIN(DEPTH) AS DEPTH
FROM ancestors GROUP BY ANCESTOR_ID, ANCESTOR_NAME ORDER BY DEPTH, ANCESTOR_NAME
$$;

CREATE OR REPLACE FUNCTION SAP_SUPPLY_CHAIN.ONTOLOGY.EXPAND_DESCENDANTS_TOOL(ROOT_CONCEPT VARCHAR)
RETURNS TABLE (NODE_ID VARCHAR, NODE_NAME VARCHAR, DEPTH NUMBER, PATH VARCHAR)
LANGUAGE SQL
COMMENT='Returns all descendants of a root concept in the ontology hierarchy, including the root at depth 0.'
AS
$$
WITH RECURSIVE
root_node AS (
    SELECT NODE_ID, NAME FROM SAP_SUPPLY_CHAIN.ONTOLOGY.KG_NODE
    WHERE LOWER(NAME) = LOWER(ROOT_CONCEPT) AND NODE_TYPE = 'OntologyClass'
    ORDER BY NODE_ID LIMIT 1
),
descendants AS (
    SELECT e.SRC_ID AS NODE_ID, n.NAME AS NODE_NAME, 1 AS DEPTH,
           r.NAME || ' -> ' || n.NAME AS PATH
    FROM SAP_SUPPLY_CHAIN.ONTOLOGY.KG_EDGE e
    JOIN root_node r ON e.DST_ID = r.NODE_ID
    JOIN SAP_SUPPLY_CHAIN.ONTOLOGY.KG_NODE n ON e.SRC_ID = n.NODE_ID
    WHERE e.EDGE_TYPE = 'subClassOf'
    UNION ALL
    SELECT e.SRC_ID, n.NAME, d.DEPTH + 1, d.PATH || ' -> ' || n.NAME
    FROM descendants d
    JOIN SAP_SUPPLY_CHAIN.ONTOLOGY.KG_EDGE e ON d.NODE_ID = e.DST_ID
    JOIN SAP_SUPPLY_CHAIN.ONTOLOGY.KG_NODE n ON e.SRC_ID = n.NODE_ID
    WHERE e.EDGE_TYPE = 'subClassOf' AND d.DEPTH < 15
)
SELECT NODE_ID, NAME AS NODE_NAME, 0 AS DEPTH, NAME AS PATH FROM root_node
UNION ALL
SELECT NODE_ID, NODE_NAME, DEPTH, PATH FROM descendants
ORDER BY DEPTH, NODE_NAME
$$;

CREATE OR REPLACE FUNCTION SAP_SUPPLY_CHAIN.ONTOLOGY.GET_DIRECT_CHILDREN_TOOL(PARENT_CONCEPT VARCHAR)
RETURNS TABLE (CHILD_ID VARCHAR, CHILD_NAME VARCHAR, CHILD_TYPE VARCHAR)
LANGUAGE SQL
COMMENT='Returns the immediate children of a concept, one level only.'
AS
$$
WITH parent_node AS (
    SELECT NODE_ID FROM SAP_SUPPLY_CHAIN.ONTOLOGY.KG_NODE
    WHERE LOWER(NAME) = LOWER(PARENT_CONCEPT) AND NODE_TYPE = 'OntologyClass'
    ORDER BY NODE_ID LIMIT 1
)
SELECT n.NODE_ID AS CHILD_ID, n.NAME AS CHILD_NAME, n.NODE_TYPE AS CHILD_TYPE
FROM parent_node p
JOIN SAP_SUPPLY_CHAIN.ONTOLOGY.KG_EDGE e ON e.DST_ID = p.NODE_ID AND e.EDGE_TYPE = 'subClassOf'
JOIN SAP_SUPPLY_CHAIN.ONTOLOGY.KG_NODE n ON n.NODE_ID = e.SRC_ID
ORDER BY n.NAME
$$;

CREATE OR REPLACE FUNCTION SAP_SUPPLY_CHAIN.ONTOLOGY.GET_HIERARCHY_PATH_TOOL(START_CONCEPT VARCHAR, END_CONCEPT VARCHAR)
RETURNS TABLE (STEP NUMBER, NODE_ID VARCHAR, NODE_NAME VARCHAR, RELATIONSHIP VARCHAR)
LANGUAGE SQL
COMMENT='Returns the subClassOf path between two concepts, step by step.'
AS
$$
WITH RECURSIVE
s AS (SELECT NODE_ID, NAME FROM SAP_SUPPLY_CHAIN.ONTOLOGY.KG_NODE
      WHERE LOWER(NAME) = LOWER(START_CONCEPT) AND NODE_TYPE = 'OntologyClass'
      ORDER BY NODE_ID LIMIT 1),
walk AS (
    SELECT 0 AS STEP, NODE_ID, NAME AS NODE_NAME, CAST(NULL AS VARCHAR) AS RELATIONSHIP FROM s
    UNION ALL
    SELECT w.STEP + 1, e.DST_ID, n.NAME, 'subClassOf'
    FROM walk w
    JOIN SAP_SUPPLY_CHAIN.ONTOLOGY.KG_EDGE e ON e.SRC_ID = w.NODE_ID AND e.EDGE_TYPE = 'subClassOf'
    JOIN SAP_SUPPLY_CHAIN.ONTOLOGY.KG_NODE n ON n.NODE_ID = e.DST_ID
    WHERE w.STEP < 20
      AND LOWER(w.NODE_NAME) <> LOWER(END_CONCEPT)
)
SELECT STEP, NODE_ID, NODE_NAME, RELATIONSHIP FROM walk ORDER BY STEP
$$;
