-- Stored-procedure wrappers around the graph traversal UDTFs.
-- Cortex Agent `type: function` resources resolve SCALAR functions only, so the
-- table functions cannot be registered directly. Each wrapper runs the UDTF and
-- returns a JSON array, which the agent can read.

CREATE OR REPLACE PROCEDURE SAP_SUPPLY_CHAIN.ONTOLOGY.SP_EXPAND_DESCENDANTS(ROOT_CONCEPT VARCHAR)
RETURNS VARIANT LANGUAGE SQL
COMMENT = 'All descendants of an ontology class, including the class itself, with depth and path.'
AS
$$
DECLARE res VARIANT;
BEGIN
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT('class', NODE_NAME, 'depth', DEPTH, 'path', PATH))
           WITHIN GROUP (ORDER BY DEPTH, NODE_NAME)
    INTO :res
    FROM TABLE(SAP_SUPPLY_CHAIN.ONTOLOGY.EXPAND_DESCENDANTS_TOOL(:ROOT_CONCEPT));
  RETURN COALESCE(:res, TO_VARIANT(ARRAY_CONSTRUCT()));
END;
$$;

CREATE OR REPLACE PROCEDURE SAP_SUPPLY_CHAIN.ONTOLOGY.SP_GET_ANCESTORS(CONCEPT VARCHAR)
RETURNS VARIANT LANGUAGE SQL
COMMENT = 'All ancestors of an ontology class with the shortest depth to each.'
AS
$$
DECLARE res VARIANT;
BEGIN
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT('class', ANCESTOR_NAME, 'depth', DEPTH))
           WITHIN GROUP (ORDER BY DEPTH, ANCESTOR_NAME)
    INTO :res
    FROM TABLE(SAP_SUPPLY_CHAIN.ONTOLOGY.GET_ANCESTORS_TOOL(:CONCEPT));
  RETURN COALESCE(:res, TO_VARIANT(ARRAY_CONSTRUCT()));
END;
$$;

CREATE OR REPLACE PROCEDURE SAP_SUPPLY_CHAIN.ONTOLOGY.SP_GET_DIRECT_CHILDREN(PARENT_CONCEPT VARCHAR)
RETURNS VARIANT LANGUAGE SQL
COMMENT = 'Immediate children of an ontology class, one level only.'
AS
$$
DECLARE res VARIANT;
BEGIN
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT('class', CHILD_NAME, 'type', CHILD_TYPE))
           WITHIN GROUP (ORDER BY CHILD_NAME)
    INTO :res
    FROM TABLE(SAP_SUPPLY_CHAIN.ONTOLOGY.GET_DIRECT_CHILDREN_TOOL(:PARENT_CONCEPT));
  RETURN COALESCE(:res, TO_VARIANT(ARRAY_CONSTRUCT()));
END;
$$;

CREATE OR REPLACE PROCEDURE SAP_SUPPLY_CHAIN.ONTOLOGY.SP_GET_HIERARCHY_PATH(START_CONCEPT VARCHAR, END_CONCEPT VARCHAR)
RETURNS VARIANT LANGUAGE SQL
COMMENT = 'The subClassOf path between two ontology classes, step by step.'
AS
$$
DECLARE res VARIANT;
BEGIN
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT('step', STEP, 'class', NODE_NAME, 'relationship', RELATIONSHIP))
           WITHIN GROUP (ORDER BY STEP)
    INTO :res
    FROM TABLE(SAP_SUPPLY_CHAIN.ONTOLOGY.GET_HIERARCHY_PATH_TOOL(:START_CONCEPT, :END_CONCEPT));
  RETURN COALESCE(:res, TO_VARIANT(ARRAY_CONSTRUCT()));
END;
$$;
